server:
  port: 8001

eureka:
  instance:                         #Eureka实例
    hostname: eureka.itheima.com #Eureka实例所在的主机名

  client:
    service-url:
      defaultZone: http://eureka.itheima.com:8001/eureka

    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true

spring:
  application:
      name: cold-eureka-server